import { PrismaClient, ExerciseCategory, MuscleGroup } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🏋️ Starting weightlifting exercises seed...');

  // Create admin user if not exists
  const hashedPassword = await bcrypt.hash('Admin123!', 10);
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@epicfitness.com' },
    update: {},
    create: {
      email: 'admin@epicfitness.com',
      username: 'admin',
      password: hashedPassword,
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      isEmailVerified: true,
    },
  });

  // Comprehensive weightlifting exercises (50+)
  const exercises = [
    // CHEST EXERCISES (10)
    {
      name: 'Barbell Bench Press',
      slug: 'barbell-bench-press',
      description: 'Classic chest exercise for mass and strength',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Lie on bench with eyes under bar',
        'Grip bar slightly wider than shoulder width',
        'Lower bar to chest with control',
        'Press bar up to starting position',
      ],
      tips: ['Keep feet flat on floor', 'Maintain arch in lower back', 'Keep shoulder blades retracted'],
      commonMistakes: ['Bouncing bar off chest', 'Flaring elbows too wide', 'Not using full range of motion'],
    },
    {
      name: 'Incline Dumbbell Press',
      slug: 'incline-dumbbell-press',
      description: 'Upper chest focused pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Set bench to 30-45 degree incline',
        'Hold dumbbells at chest level',
        'Press weights up and together',
        'Lower with control',
      ],
      tips: ['Keep core engaged', 'Don\'t let elbows drop too low', 'Press in slight arc'],
      commonMistakes: ['Setting bench too high', 'Losing tension at bottom', 'Not controlling descent'],
    },
    {
      name: 'Decline Bench Press',
      slug: 'decline-bench-press',
      description: 'Lower chest emphasized pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Secure feet at top of decline bench',
        'Grip bar slightly wider than shoulders',
        'Lower bar to lower chest',
        'Press up powerfully',
      ],
      tips: ['Keep core tight', 'Control the negative', 'Touch lower chest'],
      commonMistakes: ['Dropping bar too fast', 'Arching back excessively', 'Using momentum'],
    },
    {
      name: 'Cable Flyes',
      slug: 'cable-flyes',
      description: 'Isolation exercise for chest development',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Set cables at chest height',
        'Step forward with slight lean',
        'Bring hands together in arc motion',
        'Squeeze chest at peak contraction',
      ],
      tips: ['Keep slight bend in elbows', 'Focus on chest squeeze', 'Maintain consistent arc'],
      commonMistakes: ['Using too much weight', 'Bending arms too much', 'Not getting full stretch'],
    },
    {
      name: 'Dumbbell Pullover',
      slug: 'dumbbell-pullover',
      description: 'Chest and lat expansion exercise',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Lie perpendicular on bench',
        'Hold dumbbell with both hands overhead',
        'Lower weight behind head in arc',
        'Return to starting position',
      ],
      tips: ['Keep hips low', 'Focus on stretch', 'Breathe deeply'],
      commonMistakes: ['Bending arms too much', 'Going too heavy', 'Raising hips'],
    },
    {
      name: 'Chest Dips',
      slug: 'chest-dips',
      description: 'Compound movement for lower chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dip bars',
      instructions: [
        'Lean forward on dip bars',
        'Lower body with control',
        'Feel stretch in chest',
        'Push up focusing on chest',
      ],
      tips: ['Lean forward for chest emphasis', 'Control descent', 'Keep elbows slightly flared'],
      commonMistakes: ['Going too low', 'Using momentum', 'Not leaning forward'],
    },
    {
      name: 'Machine Chest Press',
      slug: 'machine-chest-press',
      description: 'Controlled chest pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Chest press machine',
      instructions: [
        'Adjust seat to proper height',
        'Grip handles at chest level',
        'Press forward with control',
        'Return slowly to start',
      ],
      tips: ['Keep back against pad', 'Exhale on press', 'Full range of motion'],
      commonMistakes: ['Partial reps', 'Locking elbows', 'Using momentum'],
    },
    {
      name: 'Close-Grip Bench Press',
      slug: 'close-grip-bench-press',
      description: 'Tricep-focused bench press variation',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Grip bar at shoulder width',
        'Keep elbows tucked',
        'Lower bar to lower chest',
        'Press straight up',
      ],
      tips: ['Keep elbows close to body', 'Focus on triceps', 'Maintain wrist alignment'],
      commonMistakes: ['Grip too narrow', 'Flaring elbows', 'Bouncing bar'],
    },
    {
      name: 'Pec Deck Machine',
      slug: 'pec-deck-machine',
      description: 'Isolation exercise for chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Pec deck machine',
      instructions: [
        'Sit with back against pad',
        'Place forearms on pads',
        'Bring arms together',
        'Squeeze chest at peak',
      ],
      tips: ['Keep shoulders down', 'Control movement', 'Focus on chest contraction'],
      commonMistakes: ['Using shoulders', 'Partial range', 'Going too fast'],
    },
    {
      name: 'Landmine Press',
      slug: 'landmine-press',
      description: 'Angled pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell with landmine',
      instructions: [
        'Hold end of barbell at chest',
        'Press up and forward',
        'Squeeze chest at top',
        'Lower with control',
      ],
      tips: ['Keep core tight', 'Press in arc motion', 'Use both arms or single arm'],
      commonMistakes: ['Leaning back', 'Using legs', 'Not controlling weight'],
    },

    // BACK EXERCISES (10)
    {
      name: 'Deadlift',
      slug: 'deadlift',
      description: 'King of all exercises for total body strength',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Stand with feet hip-width apart',
        'Grip bar just outside legs',
        'Keep back straight, chest up',
        'Drive through heels to stand',
        'Lock out hips and knees at top',
      ],
      tips: ['Keep bar close to body', 'Engage lats', 'Push floor away'],
      commonMistakes: ['Rounding back', 'Bar drifting away', 'Hyperextending at top'],
    },
    {
      name: 'Bent Over Barbell Row',
      slug: 'bent-over-barbell-row',
      description: 'Mass builder for back thickness',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hinge at hips with knees slightly bent',
        'Grip bar slightly wider than shoulders',
        'Pull bar to lower chest/upper abdomen',
        'Squeeze shoulder blades together',
      ],
      tips: ['Keep core tight', 'Pull elbows back', 'Maintain hip angle'],
      commonMistakes: ['Standing too upright', 'Using momentum', 'Not retracting scapula'],
    },
    {
      name: 'Lat Pulldown',
      slug: 'lat-pulldown',
      description: 'Vertical pulling for lat width',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Grip bar wider than shoulders',
        'Lean back slightly',
        'Pull bar to upper chest',
        'Control the return',
      ],
      tips: ['Lead with elbows', 'Squeeze lats', 'Don\'t swing'],
      commonMistakes: ['Pulling behind neck', 'Using momentum', 'Grip too wide'],
    },
    {
      name: 'T-Bar Row',
      slug: 't-bar-row',
      description: 'Thick back builder with stable position',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'T-bar machine or barbell',
      instructions: [
        'Straddle bar with bent knees',
        'Keep chest up, back straight',
        'Pull weight to chest',
        'Squeeze back at top',
      ],
      tips: ['Keep core engaged', 'Use different grips', 'Control negative'],
      commonMistakes: ['Rounding back', 'Standing too upright', 'Using arms only'],
    },
    {
      name: 'Single Arm Dumbbell Row',
      slug: 'single-arm-dumbbell-row',
      description: 'Unilateral back exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Place knee and hand on bench',
        'Keep back parallel to floor',
        'Pull dumbbell to hip',
        'Lower with control',
      ],
      tips: ['Don\'t rotate torso', 'Pull elbow back', 'Squeeze at top'],
      commonMistakes: ['Rotating body', 'Pulling to shoulder', 'Using momentum'],
    },
    {
      name: 'Cable Row',
      slug: 'cable-row',
      description: 'Seated horizontal pulling movement',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Sit with knees slightly bent',
        'Keep back straight',
        'Pull handle to abdomen',
        'Squeeze shoulder blades',
      ],
      tips: ['Don\'t lean back', 'Keep chest up', 'Full stretch forward'],
      commonMistakes: ['Rocking motion', 'Rounding back', 'Partial reps'],
    },
    {
      name: 'Rack Pulls',
      slug: 'rack-pulls',
      description: 'Partial deadlift for back thickness',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell in rack',
      instructions: [
        'Set bar at knee height',
        'Grip and stand like deadlift',
        'Pull to lockout',
        'Focus on back contraction',
      ],
      tips: ['Go heavy', 'Squeeze traps at top', 'Use straps if needed'],
      commonMistakes: ['Setting bar too high', 'Not locking out', 'Hyperextending'],
    },
    {
      name: 'Face Pulls',
      slug: 'face-pulls',
      description: 'Rear delt and upper back exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable with rope',
      instructions: [
        'Set cable at face height',
        'Pull rope to face',
        'Separate hands at face',
        'Squeeze shoulder blades',
      ],
      tips: ['Keep elbows high', 'External rotation at end', 'Light weight high reps'],
      commonMistakes: ['Elbows dropping', 'Using biceps', 'Leaning back'],
    },
    {
      name: 'Shrugs',
      slug: 'shrugs',
      description: 'Trapezius isolation exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells or barbell',
      instructions: [
        'Hold weights at sides',
        'Shrug shoulders straight up',
        'Squeeze traps at top',
        'Lower with control',
      ],
      tips: ['Don\'t roll shoulders', 'Pause at top', 'Go heavy'],
      commonMistakes: ['Rolling shoulders', 'Using arms', 'Partial range'],
    },
    {
      name: 'Straight Arm Pulldown',
      slug: 'straight-arm-pulldown',
      description: 'Lat isolation exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Stand facing cable',
        'Keep arms straight',
        'Pull bar to thighs',
        'Focus on lat contraction',
      ],
      tips: ['Slight forward lean', 'Keep arms locked', 'Use lats not arms'],
      commonMistakes: ['Bending elbows', 'Using triceps', 'Standing upright'],
    },

    // SHOULDER EXERCISES (10)
    {
      name: 'Military Press',
      slug: 'military-press',
      description: 'Strict overhead barbell press',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Grip bar at shoulder width',
        'Keep core tight',
        'Press bar straight up',
        'Lock out overhead',
      ],
      tips: ['Keep elbows forward', 'Squeeze glutes', 'Full lockout'],
      commonMistakes: ['Arching back', 'Press behind head', 'Using legs'],
    },
    {
      name: 'Dumbbell Shoulder Press',
      slug: 'dumbbell-shoulder-press',
      description: 'Seated or standing overhead press',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold dumbbells at shoulder level',
        'Press weights overhead',
        'Bring weights together at top',
        'Lower with control',
      ],
      tips: ['Keep core engaged', 'Don\'t lock elbows', 'Control descent'],
      commonMistakes: ['Arching back', 'Partial reps', 'Swinging weights'],
    },
    {
      name: 'Lateral Raises',
      slug: 'lateral-raises',
      description: 'Isolation for side delts',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold weights at sides',
        'Raise arms to parallel',
        'Lead with elbows',
        'Control the descent',
      ],
      tips: ['Slight forward lean', 'Don\'t go too high', 'Light weight'],
      commonMistakes: ['Using momentum', 'Going too heavy', 'Shrugging'],
    },
    {
      name: 'Front Raises',
      slug: 'front-raises',
      description: 'Front deltoid isolation',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells or barbell',
      instructions: [
        'Hold weights in front',
        'Raise to eye level',
        'Keep arms straight',
        'Lower slowly',
      ],
      tips: ['Alternate arms', 'Control movement', 'Don\'t swing'],
      commonMistakes: ['Going too high', 'Using back', 'Momentum'],
    },
    {
      name: 'Arnold Press',
      slug: 'arnold-press',
      description: 'Rotating dumbbell press for full delt development',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Start with palms facing you',
        'Rotate while pressing up',
        'End with palms forward',
        'Reverse on descent',
      ],
      tips: ['Smooth rotation', 'Full range', 'Control weight'],
      commonMistakes: ['Rushing rotation', 'Partial reps', 'Too heavy'],
    },
    {
      name: 'Upright Row',
      slug: 'upright-row',
      description: 'Compound shoulder and trap exercise',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell or dumbbells',
      instructions: [
        'Hold weight in front',
        'Pull up along body',
        'Lead with elbows',
        'Elbows higher than hands',
      ],
      tips: ['Wide grip safer', 'Don\'t go too high', 'Control movement'],
      commonMistakes: ['Narrow grip', 'Internal rotation', 'Using momentum'],
    },
    {
      name: 'Reverse Flyes',
      slug: 'reverse-flyes',
      description: 'Rear deltoid isolation',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Bend forward at hips',
        'Arms hang down',
        'Raise arms to sides',
        'Squeeze rear delts',
      ],
      tips: ['Light weight', 'Lead with pinkies', 'Keep back straight'],
      commonMistakes: ['Too heavy', 'Using back', 'Momentum'],
    },
    {
      name: 'Cable Lateral Raises',
      slug: 'cable-lateral-raises',
      description: 'Constant tension lateral raise',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Set cable at bottom',
        'Stand sideways to cable',
        'Raise arm to side',
        'Control descent',
      ],
      tips: ['Behind back variation', 'Constant tension', 'Full range'],
      commonMistakes: ['Leaning', 'Using trap', 'Going too high'],
    },
    {
      name: 'Bradford Press',
      slug: 'bradford-press',
      description: 'Unique shoulder press variation',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Press bar to forehead height',
        'Move bar over head',
        'Lower behind head slightly',
        'Return over head to front',
      ],
      tips: ['Light weight', 'Control movement', 'Don\'t go too low'],
      commonMistakes: ['Going too low behind', 'Heavy weight', 'Fast movement'],
    },
    {
      name: 'Machine Shoulder Press',
      slug: 'machine-shoulder-press',
      description: 'Controlled shoulder pressing',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Shoulder press machine',
      instructions: [
        'Adjust seat height',
        'Grip handles',
        'Press up with control',
        'Don\'t lock out',
      ],
      tips: ['Full range', 'Exhale on press', 'Keep back against pad'],
      commonMistakes: ['Partial reps', 'Arching back', 'Too fast'],
    },

    // LEG EXERCISES (10)
    {
      name: 'Back Squat',
      slug: 'back-squat',
      description: 'The king of leg exercises',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar on upper traps',
        'Feet shoulder width apart',
        'Squat down to parallel or below',
        'Drive through heels to stand',
      ],
      tips: ['Keep chest up', 'Knees track toes', 'Hip drive out of bottom'],
      commonMistakes: ['Knees caving', 'Butt wink', 'Not hitting depth'],
    },
    {
      name: 'Front Squat',
      slug: 'front-squat',
      description: 'Quad-dominant squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar in front rack position',
        'Elbows high',
        'Squat straight down',
        'Keep torso upright',
      ],
      tips: ['Flexible wrists', 'Core tight', 'Elbows up'],
      commonMistakes: ['Elbows dropping', 'Leaning forward', 'Losing rack position'],
    },
    {
      name: 'Romanian Deadlift',
      slug: 'romanian-deadlift',
      description: 'Hamstring and glute focused deadlift',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Start standing with bar',
        'Push hips back',
        'Lower bar along legs',
        'Feel stretch in hamstrings',
      ],
      tips: ['Soft knees', 'Hip hinge', 'Bar stays close'],
      commonMistakes: ['Bending knees too much', 'Rounding back', 'Going too low'],
    },
    {
      name: 'Leg Press',
      slug: 'leg-press',
      description: 'Machine-based leg exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg press machine',
      instructions: [
        'Sit in machine',
        'Feet shoulder width on platform',
        'Lower weight with control',
        'Press through heels',
      ],
      tips: ['Don\'t lock knees', 'Full range', 'Various foot positions'],
      commonMistakes: ['Partial reps', 'Knees caving', 'Lower back rounding'],
    },
    {
      name: 'Walking Lunges',
      slug: 'walking-lunges',
      description: 'Dynamic unilateral leg exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells or barbell',
      instructions: [
        'Step forward into lunge',
        'Lower back knee toward floor',
        'Push off front foot',
        'Step forward with other leg',
      ],
      tips: ['Long steps', 'Torso upright', 'Knee behind toes'],
      commonMistakes: ['Short steps', 'Leaning forward', 'Knee past toes'],
    },
    {
      name: 'Leg Curl',
      slug: 'leg-curl',
      description: 'Hamstring isolation exercise',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg curl machine',
      instructions: [
        'Lie face down on machine',
        'Curl heels toward glutes',
        'Squeeze hamstrings',
        'Lower with control',
      ],
      tips: ['Point toes', 'Full range', 'Don\'t hyperextend back'],
      commonMistakes: ['Using momentum', 'Partial reps', 'Lifting hips'],
    },
    {
      name: 'Leg Extension',
      slug: 'leg-extension',
      description: 'Quadriceps isolation exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg extension machine',
      instructions: [
        'Sit on machine',
        'Position legs under pads',
        'Extend legs fully',
        'Lower with control',
      ],
      tips: ['Don\'t lock out hard', 'Control descent', 'Full range'],
      commonMistakes: ['Swinging legs', 'Partial reps', 'Too fast'],
    },
    {
      name: 'Bulgarian Split Squat',
      slug: 'bulgarian-split-squat',
      description: 'Single leg squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Bench and dumbbells',
      instructions: [
        'Rear foot on bench',
        'Lower into lunge position',
        'Drive through front heel',
        'Keep torso upright',
      ],
      tips: ['Don\'t push off back foot', 'Knee tracks toes', 'Control descent'],
      commonMistakes: ['Leaning forward', 'Back foot too high', 'Short range'],
    },
    {
      name: 'Calf Raises',
      slug: 'calf-raises',
      description: 'Calf muscle isolation',
      primaryMuscle: 'CALVES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Machine or dumbbells',
      instructions: [
        'Stand on balls of feet',
        'Rise up on toes',
        'Squeeze calves at top',
        'Lower slowly',
      ],
      tips: ['Full range', 'Pause at top', 'Slow negative'],
      commonMistakes: ['Bouncing', 'Partial reps', 'Too fast'],
    },
    {
      name: 'Hack Squat',
      slug: 'hack-squat',
      description: 'Machine squat for quad development',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Hack squat machine',
      instructions: [
        'Position shoulders under pads',
        'Feet shoulder width apart',
        'Squat down with control',
        'Drive through heels',
      ],
      tips: ['Various foot positions', 'Full depth', 'Don\'t lock knees'],
      commonMistakes: ['Partial reps', 'Knees caving', 'Bouncing'],
    },

    // ARM EXERCISES - BICEPS (5)
    {
      name: 'Barbell Curl',
      slug: 'barbell-curl',
      description: 'Classic bicep mass builder',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hold bar with underhand grip',
        'Keep elbows at sides',
        'Curl bar to chest',
        'Lower with control',
      ],
      tips: ['Don\'t swing', 'Squeeze at top', 'Full range'],
      commonMistakes: ['Swinging body', 'Elbows forward', 'Partial reps'],
    },
    {
      name: 'Hammer Curls',
      slug: 'hammer-curls',
      description: 'Neutral grip curl for brachialis',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold dumbbells with neutral grip',
        'Keep palms facing each other',
        'Curl weights to shoulders',
        'Control the descent',
      ],
      tips: ['Keep wrists straight', 'Don\'t rotate', 'Alternate or together'],
      commonMistakes: ['Rotating wrists', 'Swinging', 'Elbows drifting'],
    },
    {
      name: 'Preacher Curl',
      slug: 'preacher-curl',
      description: 'Isolated bicep exercise',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Preacher bench and barbell',
      instructions: [
        'Position arms on preacher pad',
        'Grip bar with underhand grip',
        'Curl weight up',
        'Lower slowly',
      ],
      tips: ['Don\'t hyperextend', 'Full contraction', 'Control negative'],
      commonMistakes: ['Dropping weight', 'Partial reps', 'Lifting shoulders'],
    },
    {
      name: 'Cable Curl',
      slug: 'cable-curl',
      description: 'Constant tension bicep curl',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Attach bar to low cable',
        'Stand facing cable',
        'Curl bar to chest',
        'Control descent',
      ],
      tips: ['Keep elbows stationary', 'Various attachments', 'Squeeze peak'],
      commonMistakes: ['Leaning back', 'Elbows drifting', 'Momentum'],
    },
    {
      name: 'Concentration Curl',
      slug: 'concentration-curl',
      description: 'Peak contraction bicep exercise',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Sit with elbow on inner thigh',
        'Curl weight to shoulder',
        'Squeeze bicep hard',
        'Lower slowly',
      ],
      tips: ['Rotate wrist at top', 'Full contraction', 'No swinging'],
      commonMistakes: ['Using shoulder', 'Partial reps', 'Moving elbow'],
    },

    // ARM EXERCISES - TRICEPS (5)
    {
      name: 'Tricep Dips',
      slug: 'tricep-dips',
      description: 'Bodyweight tricep exercise',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dip bars or bench',
      instructions: [
        'Support body on bars',
        'Keep body upright',
        'Lower with elbows back',
        'Push up to lockout',
      ],
      tips: ['Stay upright for triceps', 'Control descent', 'Full lockout'],
      commonMistakes: ['Leaning forward', 'Partial reps', 'Shoulders forward'],
    },
    {
      name: 'Overhead Tricep Extension',
      slug: 'overhead-tricep-extension',
      description: 'Long head tricep emphasis',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell or barbell',
      instructions: [
        'Hold weight overhead',
        'Lower behind head',
        'Keep elbows in',
        'Extend to start',
      ],
      tips: ['Elbows stationary', 'Full stretch', 'Control weight'],
      commonMistakes: ['Elbows flaring', 'Partial range', 'Arching back'],
    },
    {
      name: 'Cable Pushdown',
      slug: 'cable-pushdown',
      description: 'Tricep isolation with cable',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Stand at cable machine',
        'Keep elbows at sides',
        'Push weight down',
        'Squeeze triceps at bottom',
      ],
      tips: ['Various grips', 'Lock elbows in place', 'Full extension'],
      commonMistakes: ['Elbows drifting', 'Leaning over', 'Momentum'],
    },
    {
      name: 'Diamond Push-ups',
      slug: 'diamond-push-ups',
      description: 'Bodyweight tricep focused push-up',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Make diamond with hands',
        'Lower chest to hands',
        'Keep elbows close',
        'Push up to start',
      ],
      tips: ['Core tight', 'Elbows in', 'Full range'],
      commonMistakes: ['Elbows flaring', 'Partial reps', 'Sagging hips'],
    },
    {
      name: 'Skull Crushers',
      slug: 'skull-crushers',
      description: 'Lying tricep extension',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell or dumbbells',
      instructions: [
        'Lie on bench with weight overhead',
        'Lower weight to forehead',
        'Keep elbows stationary',
        'Extend back to start',
      ],
      tips: ['Control descent', 'Elbows in', 'Various angles'],
      commonMistakes: ['Elbows flaring', 'Going too heavy', 'Dropping weight'],
    },

    // GLUTE EXERCISES (5)
    {
      name: 'Hip Thrust',
      slug: 'hip-thrust',
      description: 'Primary glute building exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell and bench',
      instructions: [
        'Shoulders on bench',
        'Bar on hips',
        'Drive hips up',
        'Squeeze glutes at top',
      ],
      tips: ['Pause at top', 'Full hip extension', 'Chin tucked'],
      commonMistakes: ['Arching back', 'Not locking out', 'Feet too far'],
    },
    {
      name: 'Glute Bridge',
      slug: 'glute-bridge',
      description: 'Floor-based glute exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Optional barbell',
      instructions: [
        'Lie on back',
        'Feet flat on floor',
        'Drive hips up',
        'Squeeze glutes',
      ],
      tips: ['Hold at top', 'Single leg variation', 'Add weight'],
      commonMistakes: ['Using lower back', 'Feet too far', 'Not squeezing'],
    },
    {
      name: 'Cable Pull Through',
      slug: 'cable-pull-through',
      description: 'Hip hinge for glutes',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable machine',
      instructions: [
        'Face away from cable',
        'Rope between legs',
        'Hinge at hips',
        'Drive hips forward',
      ],
      tips: ['Push hips back', 'Squeeze glutes', 'Keep back straight'],
      commonMistakes: ['Squatting down', 'Rounding back', 'Not locking out'],
    },
    {
      name: 'Glute Kickbacks',
      slug: 'glute-kickbacks',
      description: 'Isolation for glutes',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable or machine',
      instructions: [
        'Attach ankle to cable',
        'Kick leg back',
        'Squeeze glute',
        'Control return',
      ],
      tips: ['Keep leg straight', 'Don\'t arch back', 'Full contraction'],
      commonMistakes: ['Using momentum', 'Rotating hips', 'Hyperextending back'],
    },
    {
      name: 'Good Mornings',
      slug: 'good-mornings',
      description: 'Posterior chain exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar on upper back',
        'Hinge at hips',
        'Keep back straight',
        'Return to standing',
      ],
      tips: ['Start light', 'Soft knees', 'Feel stretch'],
      commonMistakes: ['Rounding back', 'Going too heavy', 'Bending knees too much'],
    },
  ];

  console.log(`📝 Seeding ${exercises.length} weightlifting exercises...`);

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      update: {},
      create: exercise,
    });
    console.log(`  ✓ ${exercise.name}`);
  }

  console.log(`\n✅ Successfully seeded ${exercises.length} weightlifting exercises!`);
  console.log('🎉 Database seed completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });