import { PrismaClient, ExerciseCategory, MuscleGroup } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting comprehensive database seed...');

  // Create admin user
  const hashedPassword = await bcrypt.hash('Admin123!', 10);
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@epicfitness.com' },
    update: {},
    create: {
      email: 'admin@epicfitness.com',
      username: 'admin',
      password: hashedPassword,
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      isEmailVerified: true,
    },
  });

  console.log('✅ Admin user created');

  // Comprehensive exercise list - 100 exercises
  const exercises = [
    // CHEST EXERCISES (15)
    {
      name: 'Barbell Bench Press',
      slug: 'barbell-bench-press',
      description: 'Classic chest exercise targeting the pectorals, shoulders, and triceps',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Lie flat on bench with eyes under bar',
        'Grip bar slightly wider than shoulder width',
        'Lower bar to chest with control',
        'Press bar back up to starting position',
      ],
      tips: ['Keep feet flat on floor', 'Maintain arch in lower back'],
      commonMistakes: ['Bouncing bar off chest', 'Flaring elbows too wide'],
    },
    {
      name: 'Dumbbell Bench Press',
      slug: 'dumbbell-bench-press',
      description: 'Chest press variation allowing greater range of motion',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Lie on bench with dumbbells at chest level',
        'Press dumbbells up and together',
        'Lower with control to chest level',
      ],
      tips: ['Keep core engaged', 'Control the descent'],
      commonMistakes: ['Going too heavy', 'Losing control at bottom'],
    },
    {
      name: 'Incline Barbell Press',
      slug: 'incline-barbell-press',
      description: 'Upper chest focused pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Set bench to 30-45 degree incline',
        'Grip bar slightly wider than shoulders',
        'Lower bar to upper chest',
        'Press back to starting position',
      ],
      tips: ['Keep shoulder blades retracted', 'Drive feet into floor'],
      commonMistakes: ['Setting bench too steep', 'Arching back excessively'],
    },
    {
      name: 'Decline Bench Press',
      slug: 'decline-bench-press',
      description: 'Lower chest focused pressing movement',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Secure feet at top of decline bench',
        'Grip bar shoulder width apart',
        'Lower bar to lower chest',
        'Press back up to start',
      ],
      tips: ['Keep core tight', 'Control the weight'],
      commonMistakes: ['Using too steep decline', 'Losing tightness'],
    },
    {
      name: 'Push-ups',
      slug: 'push-ups',
      description: 'Classic bodyweight chest exercise',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Start in plank position',
        'Lower chest to floor',
        'Push back up to start',
      ],
      tips: ['Keep body straight', 'Full range of motion'],
      commonMistakes: ['Sagging hips', 'Partial reps'],
    },
    {
      name: 'Diamond Push-ups',
      slug: 'diamond-push-ups',
      description: 'Close-grip push-up variation for triceps and inner chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Form diamond shape with hands',
        'Lower chest to hands',
        'Push back up',
      ],
      tips: ['Keep elbows close', 'Maintain form'],
      commonMistakes: ['Hands too far apart', 'Flaring elbows'],
    },
    {
      name: 'Wide-Grip Push-ups',
      slug: 'wide-grip-push-ups',
      description: 'Push-up variation emphasizing outer chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Place hands wider than shoulders',
        'Lower chest to floor',
        'Push back up',
      ],
      tips: ['Keep core engaged', 'Control movement'],
      commonMistakes: ['Going too wide', 'Losing form'],
    },
    {
      name: 'Dumbbell Flyes',
      slug: 'dumbbell-flyes',
      description: 'Isolation exercise for chest development',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Lie on bench with dumbbells extended above',
        'Lower weights in wide arc',
        'Squeeze chest to bring dumbbells together',
      ],
      tips: ['Slight bend in elbows', 'Feel chest stretch'],
      commonMistakes: ['Going too heavy', 'Straightening arms'],
    },
    {
      name: 'Cable Flyes',
      slug: 'cable-flyes',
      description: 'Cable machine chest isolation exercise',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Set cables at chest height',
        'Bring handles together in front',
        'Control return to start',
      ],
      tips: ['Keep slight forward lean', 'Squeeze at peak'],
      commonMistakes: ['Using momentum', 'Bending arms too much'],
    },
    {
      name: 'Chest Dips',
      slug: 'chest-dips',
      description: 'Bodyweight exercise for lower chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dip Bars',
      instructions: [
        'Lean forward on dip bars',
        'Lower body with control',
        'Push back up to start',
      ],
      tips: ['Lean forward for chest', 'Control descent'],
      commonMistakes: ['Going too low', 'Using momentum'],
    },
    {
      name: 'Pec Deck Machine',
      slug: 'pec-deck-machine',
      description: 'Machine-based chest isolation',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Pec Deck Machine',
      instructions: [
        'Sit with back against pad',
        'Bring arms together in front',
        'Control return',
      ],
      tips: ['Keep elbows slightly bent', 'Squeeze chest'],
      commonMistakes: ['Using shoulders', 'Partial range'],
    },
    {
      name: 'Landmine Press',
      slug: 'landmine-press',
      description: 'Angled pressing movement for chest and shoulders',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hold end of barbell at chest',
        'Press up and forward',
        'Lower with control',
      ],
      tips: ['Keep core tight', 'Press at angle'],
      commonMistakes: ['Pressing straight up', 'Losing balance'],
    },
    {
      name: 'Svend Press',
      slug: 'svend-press',
      description: 'Plate squeeze exercise for inner chest',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Weight Plate',
      instructions: [
        'Hold plate between palms at chest',
        'Press plate straight out',
        'Squeeze throughout movement',
      ],
      tips: ['Constant tension', 'Squeeze plate hard'],
      commonMistakes: ['Dropping arms', 'Losing squeeze'],
    },
    {
      name: 'Pullover',
      slug: 'pullover',
      description: 'Exercise targeting chest and lats',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Lie perpendicular on bench',
        'Lower weight behind head',
        'Pull over to chest level',
      ],
      tips: ['Keep arms slightly bent', 'Feel stretch'],
      commonMistakes: ['Bending arms too much', 'Going too low'],
    },
    {
      name: 'Clap Push-ups',
      slug: 'clap-push-ups',
      description: 'Explosive plyometric push-up variation',
      primaryMuscle: 'CHEST' as MuscleGroup,
      category: 'PLYOMETRIC' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Perform explosive push-up',
        'Clap hands at top',
        'Land softly and repeat',
      ],
      tips: ['Generate power from chest', 'Land with control'],
      commonMistakes: ['Not pushing hard enough', 'Poor landing'],
    },

    // BACK EXERCISES (15)
    {
      name: 'Pull-ups',
      slug: 'pull-ups',
      description: 'Classic bodyweight back exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Pull-up Bar',
      instructions: [
        'Hang from bar with overhand grip',
        'Pull body up until chin over bar',
        'Lower with control',
      ],
      tips: ['Engage lats', 'Full range of motion'],
      commonMistakes: ['Kipping', 'Partial reps'],
    },
    {
      name: 'Chin-ups',
      slug: 'chin-ups',
      description: 'Underhand grip pull-up variation',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Pull-up Bar',
      instructions: [
        'Hang from bar with underhand grip',
        'Pull up to bar',
        'Lower with control',
      ],
      tips: ['Use biceps and back', 'Squeeze at top'],
      commonMistakes: ['Swinging', 'Not going high enough'],
    },
    {
      name: 'Barbell Row',
      slug: 'barbell-row',
      description: 'Compound back exercise for thickness',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hinge at hips with barbell',
        'Row bar to lower chest',
        'Lower with control',
      ],
      tips: ['Keep back straight', 'Pull elbows back'],
      commonMistakes: ['Rounding back', 'Using momentum'],
    },
    {
      name: 'Dumbbell Row',
      slug: 'dumbbell-row',
      description: 'Single-arm rowing movement',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Support body with one hand on bench',
        'Row dumbbell to hip',
        'Lower with control',
      ],
      tips: ['Keep core stable', 'Full stretch at bottom'],
      commonMistakes: ['Rotating torso', 'Short range of motion'],
    },
    {
      name: 'T-Bar Row',
      slug: 't-bar-row',
      description: 'Angled rowing movement for back thickness',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'T-Bar Machine',
      instructions: [
        'Straddle bar with bent knees',
        'Row bar to chest',
        'Lower with control',
      ],
      tips: ['Keep chest up', 'Squeeze shoulder blades'],
      commonMistakes: ['Rounding back', 'Standing too upright'],
    },
    {
      name: 'Lat Pulldown',
      slug: 'lat-pulldown',
      description: 'Cable exercise for lat development',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Sit at lat pulldown machine',
        'Pull bar to upper chest',
        'Control the return',
      ],
      tips: ['Lean back slightly', 'Pull with lats'],
      commonMistakes: ['Behind neck pulling', 'Using momentum'],
    },
    {
      name: 'Cable Row',
      slug: 'cable-row',
      description: 'Seated rowing movement',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Sit with feet on platform',
        'Row handle to stomach',
        'Extend arms to return',
      ],
      tips: ['Keep back straight', 'Squeeze at peak'],
      commonMistakes: ['Leaning too far', 'Rounding back'],
    },
    {
      name: 'Deadlift',
      slug: 'deadlift',
      description: 'Full body compound movement',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Stand with feet hip-width apart',
        'Grip bar and lift with legs and back',
        'Stand tall then lower',
      ],
      tips: ['Keep bar close to body', 'Drive through heels'],
      commonMistakes: ['Rounding back', 'Bar drifting forward'],
    },
    {
      name: 'Rack Pulls',
      slug: 'rack-pulls',
      description: 'Partial deadlift for upper back',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Set bar at knee height in rack',
        'Pull bar to lockout',
        'Lower with control',
      ],
      tips: ['Focus on upper back', 'Heavy weight possible'],
      commonMistakes: ['Going too low', 'Hyperextending'],
    },
    {
      name: 'Face Pulls',
      slug: 'face-pulls',
      description: 'Rear delt and upper back exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Set cable at face height',
        'Pull rope to face',
        'Separate hands at face',
      ],
      tips: ['Pull elbows back', 'Squeeze shoulder blades'],
      commonMistakes: ['Using too much weight', 'Poor elbow position'],
    },
    {
      name: 'Shrugs',
      slug: 'shrugs',
      description: 'Trap isolation exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold weights at sides',
        'Shrug shoulders up',
        'Lower with control',
      ],
      tips: ['Straight up and down', 'Hold at top'],
      commonMistakes: ['Rolling shoulders', 'Using momentum'],
    },
    {
      name: 'Inverted Row',
      slug: 'inverted-row',
      description: 'Horizontal pulling movement',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Bar or TRX',
      instructions: [
        'Hang under bar with body straight',
        'Pull chest to bar',
        'Lower with control',
      ],
      tips: ['Keep body rigid', 'Full range of motion'],
      commonMistakes: ['Sagging hips', 'Partial reps'],
    },
    {
      name: 'Straight Arm Pulldown',
      slug: 'straight-arm-pulldown',
      description: 'Lat isolation exercise',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Stand at cable with arms extended',
        'Pull bar down to thighs',
        'Control return',
      ],
      tips: ['Keep arms straight', 'Feel lat stretch'],
      commonMistakes: ['Bending arms', 'Using shoulders'],
    },
    {
      name: 'Kroc Row',
      slug: 'kroc-row',
      description: 'High rep, heavy dumbbell row',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Use heavy dumbbell',
        'Row explosively',
        'Allow slight body English',
      ],
      tips: ['Go heavy', 'High reps'],
      commonMistakes: ['Too much rotation', 'Poor control'],
    },
    {
      name: 'Pendlay Row',
      slug: 'pendlay-row',
      description: 'Strict barbell row from floor',
      primaryMuscle: 'BACK' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar starts on floor each rep',
        'Explosively row to chest',
        'Return bar to floor',
      ],
      tips: ['Stay parallel to floor', 'Explosive pull'],
      commonMistakes: ['Rising torso', 'Bouncing bar'],
    },

    // SHOULDER EXERCISES (10)
    {
      name: 'Military Press',
      slug: 'military-press',
      description: 'Strict overhead barbell press',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Stand with bar at shoulders',
        'Press straight overhead',
        'Lower with control',
      ],
      tips: ['Keep core tight', 'Press straight up'],
      commonMistakes: ['Leaning back', 'Pressing forward'],
    },
    {
      name: 'Dumbbell Shoulder Press',
      slug: 'dumbbell-shoulder-press',
      description: 'Overhead pressing with dumbbells',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold dumbbells at shoulder level',
        'Press overhead',
        'Lower with control',
      ],
      tips: ['Keep palms forward', 'Full range of motion'],
      commonMistakes: ['Arching back', 'Partial reps'],
    },
    {
      name: 'Lateral Raises',
      slug: 'lateral-raises',
      description: 'Isolation for side delts',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold weights at sides',
        'Raise arms to shoulder height',
        'Lower with control',
      ],
      tips: ['Lead with elbows', 'Control the weight'],
      commonMistakes: ['Going too heavy', 'Using momentum'],
    },
    {
      name: 'Front Raises',
      slug: 'front-raises',
      description: 'Front delt isolation',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold weights in front',
        'Raise to shoulder height',
        'Lower slowly',
      ],
      tips: ['Keep arms straight', 'Control movement'],
      commonMistakes: ['Swinging weights', 'Going too high'],
    },
    {
      name: 'Arnold Press',
      slug: 'arnold-press',
      description: 'Rotating dumbbell press',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Start with palms facing you',
        'Rotate and press overhead',
        'Reverse the motion',
      ],
      tips: ['Smooth rotation', 'Full range of motion'],
      commonMistakes: ['Rushing movement', 'Poor rotation'],
    },
    {
      name: 'Upright Row',
      slug: 'upright-row',
      description: 'Vertical pulling for shoulders and traps',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hold bar with close grip',
        'Pull bar up to chin',
        'Lower with control',
      ],
      tips: ['Elbows lead movement', 'Keep bar close'],
      commonMistakes: ['Going too high', 'Wide grip'],
    },
    {
      name: 'Reverse Flyes',
      slug: 'reverse-flyes',
      description: 'Rear delt isolation',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Bend forward at waist',
        'Raise arms to sides',
        'Squeeze shoulder blades',
      ],
      tips: ['Keep slight bend in arms', 'Feel rear delts'],
      commonMistakes: ['Using back', 'Standing too upright'],
    },
    {
      name: 'Cable Lateral Raise',
      slug: 'cable-lateral-raise',
      description: 'Cable version of lateral raise',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Stand sideways to cable',
        'Raise arm to side',
        'Control return',
      ],
      tips: ['Constant tension', 'Smooth movement'],
      commonMistakes: ['Leaning away', 'Using momentum'],
    },
    {
      name: 'Handstand Push-ups',
      slug: 'handstand-push-ups',
      description: 'Advanced bodyweight shoulder exercise',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Kick up into handstand against wall',
        'Lower head to floor',
        'Press back up',
      ],
      tips: ['Keep core tight', 'Control descent'],
      commonMistakes: ['Arching back', 'Losing balance'],
    },
    {
      name: 'Pike Push-ups',
      slug: 'pike-push-ups',
      description: 'Bodyweight shoulder exercise',
      primaryMuscle: 'SHOULDERS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Start in pike position',
        'Lower head to floor',
        'Push back up',
      ],
      tips: ['Keep hips high', 'Vertical pressing'],
      commonMistakes: ['Hips too low', 'Wrong angle'],
    },

    // ARM EXERCISES (10)
    {
      name: 'Barbell Curl',
      slug: 'barbell-curl',
      description: 'Classic bicep builder',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hold bar with underhand grip',
        'Curl weight to chest',
        'Lower with control',
      ],
      tips: ['Keep elbows still', 'Squeeze at top'],
      commonMistakes: ['Swinging weight', 'Moving elbows'],
    },
    {
      name: 'Hammer Curl',
      slug: 'hammer-curl',
      description: 'Neutral grip bicep curl',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold dumbbells with neutral grip',
        'Curl to shoulders',
        'Lower slowly',
      ],
      tips: ['Keep palms facing', 'Control movement'],
      commonMistakes: ['Rotating wrists', 'Using momentum'],
    },
    {
      name: 'Preacher Curl',
      slug: 'preacher-curl',
      description: 'Isolated bicep exercise',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'EZ Bar',
      instructions: [
        'Rest arms on preacher bench',
        'Curl weight up',
        'Lower with control',
      ],
      tips: ['Full stretch at bottom', 'Squeeze at top'],
      commonMistakes: ['Partial reps', 'Lifting elbows'],
    },
    {
      name: 'Tricep Dips',
      slug: 'tricep-dips',
      description: 'Bodyweight tricep exercise',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dip Bars',
      instructions: [
        'Support body on bars',
        'Lower by bending elbows',
        'Push back up',
      ],
      tips: ['Stay upright for triceps', 'Control descent'],
      commonMistakes: ['Leaning forward', 'Going too low'],
    },
    {
      name: 'Overhead Tricep Extension',
      slug: 'overhead-tricep-extension',
      description: 'Overhead tricep movement',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Hold weight overhead',
        'Lower behind head',
        'Extend back up',
      ],
      tips: ['Keep elbows in', 'Full stretch'],
      commonMistakes: ['Flaring elbows', 'Partial range'],
    },
    {
      name: 'Cable Pushdown',
      slug: 'cable-pushdown',
      description: 'Cable tricep isolation',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Stand at cable machine',
        'Push rope/bar down',
        'Squeeze triceps at bottom',
      ],
      tips: ['Keep elbows locked', 'Full extension'],
      commonMistakes: ['Moving elbows', 'Leaning over'],
    },
    {
      name: 'Close-Grip Bench Press',
      slug: 'close-grip-bench-press',
      description: 'Compound tricep exercise',
      primaryMuscle: 'TRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Grip bar with hands close',
        'Lower to chest',
        'Press focusing on triceps',
      ],
      tips: ['Elbows close to body', 'Focus on triceps'],
      commonMistakes: ['Grip too close', 'Flaring elbows'],
    },
    {
      name: '21s',
      slug: '21s',
      description: 'High intensity bicep protocol',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        '7 reps bottom half',
        '7 reps top half',
        '7 reps full range',
      ],
      tips: ['No rest between parts', 'Light weight'],
      commonMistakes: ['Going too heavy', 'Resting between'],
    },
    {
      name: 'Cable Hammer Curl',
      slug: 'cable-hammer-curl',
      description: 'Cable version of hammer curl',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Use rope attachment',
        'Curl with neutral grip',
        'Control return',
      ],
      tips: ['Constant tension', 'Keep elbows still'],
      commonMistakes: ['Swinging body', 'Moving elbows'],
    },
    {
      name: 'Concentration Curl',
      slug: 'concentration-curl',
      description: 'Isolated single-arm curl',
      primaryMuscle: 'BICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Sit with elbow on inner thigh',
        'Curl weight up',
        'Squeeze and lower',
      ],
      tips: ['Full isolation', 'Peak contraction'],
      commonMistakes: ['Using momentum', 'Partial reps'],
    },

    // CORE EXERCISES (15)
    {
      name: 'Plank',
      slug: 'plank',
      description: 'Isometric core hold',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Hold push-up position on forearms',
        'Keep body straight',
        'Hold for time',
      ],
      tips: ['Engage entire core', 'Breathe normally'],
      commonMistakes: ['Sagging hips', 'Holding breath'],
    },
    {
      name: 'Bicycle Crunches',
      slug: 'bicycle-crunches',
      description: 'Rotational ab exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back, hands behind head',
        'Bring knee to opposite elbow',
        'Alternate sides',
      ],
      tips: ['Control movement', 'Don\'t pull neck'],
      commonMistakes: ['Going too fast', 'Pulling head'],
    },
    {
      name: 'Russian Twists',
      slug: 'russian-twists',
      description: 'Rotational core exercise',
      primaryMuscle: 'OBLIQUES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Medicine Ball',
      instructions: [
        'Sit with knees bent',
        'Lean back slightly',
        'Rotate side to side',
      ],
      tips: ['Keep chest up', 'Control rotation'],
      commonMistakes: ['Rounding back', 'Using arms only'],
    },
    {
      name: 'Dead Bug',
      slug: 'dead-bug',
      description: 'Core stability exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back, arms up',
        'Lower opposite arm and leg',
        'Return and switch',
      ],
      tips: ['Press lower back down', 'Slow movement'],
      commonMistakes: ['Arching back', 'Moving too fast'],
    },
    {
      name: 'Mountain Climbers',
      slug: 'mountain-climbers',
      description: 'Dynamic core and cardio',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'CARDIO' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Start in plank position',
        'Drive knees to chest alternately',
        'Keep hips level',
      ],
      tips: ['Keep core tight', 'Quick movements'],
      commonMistakes: ['Hips bouncing', 'Poor form'],
    },
    {
      name: 'Hanging Knee Raises',
      slug: 'hanging-knee-raises',
      description: 'Hanging ab exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Pull-up Bar',
      instructions: [
        'Hang from bar',
        'Raise knees to chest',
        'Lower with control',
      ],
      tips: ['Control swing', 'Full range'],
      commonMistakes: ['Swinging', 'Using momentum'],
    },
    {
      name: 'Ab Wheel Rollout',
      slug: 'ab-wheel-rollout',
      description: 'Advanced core exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Ab Wheel',
      instructions: [
        'Kneel with wheel',
        'Roll forward',
        'Pull back with abs',
      ],
      tips: ['Keep core tight', 'Control movement'],
      commonMistakes: ['Hyperextending back', 'Going too far'],
    },
    {
      name: 'Side Plank',
      slug: 'side-plank',
      description: 'Lateral core stability',
      primaryMuscle: 'OBLIQUES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on side',
        'Prop on elbow',
        'Hold body straight',
      ],
      tips: ['Stack hips', 'Don\'t sag'],
      commonMistakes: ['Hips dropping', 'Rotating'],
    },
    {
      name: 'Woodchoppers',
      slug: 'woodchoppers',
      description: 'Rotational power exercise',
      primaryMuscle: 'OBLIQUES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Stand sideways to cable',
        'Pull across body',
        'High to low motion',
      ],
      tips: ['Rotate from core', 'Control weight'],
      commonMistakes: ['Using arms only', 'Poor rotation'],
    },
    {
      name: 'Leg Raises',
      slug: 'leg-raises',
      description: 'Lower ab exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back',
        'Raise legs to vertical',
        'Lower without touching floor',
      ],
      tips: ['Press back down', 'Control descent'],
      commonMistakes: ['Arching back', 'Using momentum'],
    },
    {
      name: 'Flutter Kicks',
      slug: 'flutter-kicks',
      description: 'Dynamic lower ab exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'CARDIO' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back',
        'Lift legs slightly',
        'Kick up and down alternately',
      ],
      tips: ['Small movements', 'Keep core engaged'],
      commonMistakes: ['Legs too high', 'Arching back'],
    },
    {
      name: 'Hollow Hold',
      slug: 'hollow-hold',
      description: 'Isometric core exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back',
        'Lift shoulders and legs',
        'Hold hollow position',
      ],
      tips: ['Press back down', 'Hold everything tight'],
      commonMistakes: ['Arching back', 'Dropping legs'],
    },
    {
      name: 'Bird Dog',
      slug: 'bird-dog',
      description: 'Core stability and balance',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Start on hands and knees',
        'Extend opposite arm and leg',
        'Hold and switch',
      ],
      tips: ['Keep hips level', 'Don\'t rotate'],
      commonMistakes: ['Hip dropping', 'Arching back'],
    },
    {
      name: 'Pallof Press',
      slug: 'pallof-press',
      description: 'Anti-rotation core exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Stand sideways to cable',
        'Press handle straight out',
        'Resist rotation',
      ],
      tips: ['Keep core tight', 'Don\'t rotate'],
      commonMistakes: ['Allowing rotation', 'Using arms'],
    },
    {
      name: 'V-Ups',
      slug: 'v-ups',
      description: 'Advanced ab exercise',
      primaryMuscle: 'ABS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie flat on back',
        'Raise legs and torso together',
        'Touch toes at top',
      ],
      tips: ['Control movement', 'Full range'],
      commonMistakes: ['Using momentum', 'Partial reps'],
    },

    // LEG EXERCISES (20)
    {
      name: 'Back Squat',
      slug: 'back-squat',
      description: 'King of leg exercises',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar on upper back',
        'Squat down to parallel',
        'Drive up through heels',
      ],
      tips: ['Keep chest up', 'Knees track toes'],
      commonMistakes: ['Knees caving', 'Butt wink'],
    },
    {
      name: 'Front Squat',
      slug: 'front-squat',
      description: 'Quad-dominant squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar in front rack position',
        'Squat keeping torso upright',
        'Drive up from bottom',
      ],
      tips: ['Elbows high', 'Stay upright'],
      commonMistakes: ['Dropping elbows', 'Leaning forward'],
    },
    {
      name: 'Goblet Squat',
      slug: 'goblet-squat',
      description: 'Beginner-friendly squat',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell or Kettlebell',
      instructions: [
        'Hold weight at chest',
        'Squat between legs',
        'Stand back up',
      ],
      tips: ['Keep weight close', 'Push knees out'],
      commonMistakes: ['Weight too far out', 'Knees caving'],
    },
    {
      name: 'Bulgarian Split Squat',
      slug: 'bulgarian-split-squat',
      description: 'Single leg squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Bench',
      instructions: [
        'Rear foot elevated on bench',
        'Lower into lunge',
        'Drive up through front leg',
      ],
      tips: ['Keep torso upright', 'Control descent'],
      commonMistakes: ['Leaning forward', 'Pushing off back leg'],
    },
    {
      name: 'Lunges',
      slug: 'lunges',
      description: 'Unilateral leg exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Step forward into lunge',
        'Lower back knee',
        'Push back to start',
      ],
      tips: ['Long stride', '90-degree angles'],
      commonMistakes: ['Short steps', 'Knee past toes'],
    },
    {
      name: 'Leg Press',
      slug: 'leg-press',
      description: 'Machine-based leg exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg Press Machine',
      instructions: [
        'Sit in machine',
        'Lower weight with control',
        'Press through heels',
      ],
      tips: ['Full range of motion', 'Don\'t lock knees'],
      commonMistakes: ['Partial reps', 'Knees caving'],
    },
    {
      name: 'Romanian Deadlift',
      slug: 'romanian-deadlift',
      description: 'Hamstring and glute builder',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Hold bar at hips',
        'Push hips back',
        'Feel hamstring stretch',
      ],
      tips: ['Keep bar close', 'Soft knees'],
      commonMistakes: ['Rounding back', 'Bending knees too much'],
    },
    {
      name: 'Leg Curl',
      slug: 'leg-curl',
      description: 'Hamstring isolation',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg Curl Machine',
      instructions: [
        'Lie on machine',
        'Curl heels to glutes',
        'Lower with control',
      ],
      tips: ['Full range', 'Squeeze at top'],
      commonMistakes: ['Partial reps', 'Using momentum'],
    },
    {
      name: 'Stiff Leg Deadlift',
      slug: 'stiff-leg-deadlift',
      description: 'Hamstring focused deadlift',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Keep legs nearly straight',
        'Hinge at hips',
        'Feel deep stretch',
      ],
      tips: ['Push hips back', 'Keep back straight'],
      commonMistakes: ['Rounding back', 'Bending knees'],
    },
    {
      name: 'Walking Lunges',
      slug: 'walking-lunges',
      description: 'Dynamic lunge variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Lunge forward',
        'Step through to next lunge',
        'Continue walking',
      ],
      tips: ['Stay upright', 'Long strides'],
      commonMistakes: ['Leaning forward', 'Short steps'],
    },
    {
      name: 'Step-ups',
      slug: 'step-ups',
      description: 'Unilateral leg exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Box or Bench',
      instructions: [
        'Step onto box',
        'Drive through heel',
        'Step down with control',
      ],
      tips: ['Full foot on box', 'Don\'t push off back leg'],
      commonMistakes: ['Using momentum', 'Pushing off ground'],
    },
    {
      name: 'Hack Squat',
      slug: 'hack-squat',
      description: 'Machine squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Hack Squat Machine',
      instructions: [
        'Position in machine',
        'Squat down',
        'Press back up',
      ],
      tips: ['Full depth', 'Feet placement varies'],
      commonMistakes: ['Partial reps', 'Knees caving'],
    },
    {
      name: 'Calf Raises',
      slug: 'calf-raises',
      description: 'Calf isolation exercise',
      primaryMuscle: 'CALVES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Calf Raise Machine',
      instructions: [
        'Stand on balls of feet',
        'Raise up on toes',
        'Lower with control',
      ],
      tips: ['Full range', 'Pause at top'],
      commonMistakes: ['Bouncing', 'Partial reps'],
    },
    {
      name: 'Box Jumps',
      slug: 'box-jumps',
      description: 'Explosive plyometric exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'PLYOMETRIC' as ExerciseCategory,
      equipment: 'Plyo Box',
      instructions: [
        'Stand facing box',
        'Jump explosively onto box',
        'Step down',
      ],
      tips: ['Land softly', 'Full hip extension'],
      commonMistakes: ['Landing hard', 'Not extending hips'],
    },
    {
      name: 'Jump Squats',
      slug: 'jump-squats',
      description: 'Explosive squat variation',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'PLYOMETRIC' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Squat down',
        'Jump explosively',
        'Land softly and repeat',
      ],
      tips: ['Maximum height', 'Soft landing'],
      commonMistakes: ['Not jumping high', 'Hard landing'],
    },
    {
      name: 'Pistol Squat',
      slug: 'pistol-squat',
      description: 'Advanced single leg squat',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Stand on one leg',
        'Squat down fully',
        'Stand back up',
      ],
      tips: ['Keep other leg straight', 'Use arms for balance'],
      commonMistakes: ['Falling backward', 'Knee caving'],
    },
    {
      name: 'Wall Sits',
      slug: 'wall-sits',
      description: 'Isometric quad exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Wall',
      instructions: [
        'Back against wall',
        'Slide down to 90 degrees',
        'Hold position',
      ],
      tips: ['Thighs parallel', 'Press back into wall'],
      commonMistakes: ['Not low enough', 'Leaning forward'],
    },
    {
      name: 'Nordic Curls',
      slug: 'nordic-curls',
      description: 'Advanced hamstring exercise',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Kneel with feet anchored',
        'Lower body forward',
        'Control descent with hamstrings',
      ],
      tips: ['Slow negative', 'Use hands to push back'],
      commonMistakes: ['Going too fast', 'Bending at hips'],
    },
    {
      name: 'Single Leg RDL',
      slug: 'single-leg-rdl',
      description: 'Unilateral hamstring exercise',
      primaryMuscle: 'HAMSTRINGS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbell',
      instructions: [
        'Stand on one leg',
        'Hinge forward',
        'Return to standing',
      ],
      tips: ['Keep hips square', 'Feel stretch'],
      commonMistakes: ['Rotating hips', 'Rounding back'],
    },
    {
      name: 'Leg Extensions',
      slug: 'leg-extensions',
      description: 'Quad isolation exercise',
      primaryMuscle: 'QUADRICEPS' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Leg Extension Machine',
      instructions: [
        'Sit in machine',
        'Extend legs fully',
        'Lower with control',
      ],
      tips: ['Full extension', 'Squeeze at top'],
      commonMistakes: ['Partial reps', 'Going too fast'],
    },

    // GLUTE EXERCISES (10)
    {
      name: 'Hip Thrust',
      slug: 'hip-thrust',
      description: 'Primary glute builder',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Back on bench, bar on hips',
        'Drive hips up',
        'Squeeze glutes at top',
      ],
      tips: ['Full hip extension', 'Pause at top'],
      commonMistakes: ['Hyperextending back', 'Not squeezing'],
    },
    {
      name: 'Glute Bridge',
      slug: 'glute-bridge',
      description: 'Bodyweight glute exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie on back',
        'Drive hips up',
        'Squeeze and lower',
      ],
      tips: ['Push through heels', 'Full extension'],
      commonMistakes: ['Using lower back', 'Partial reps'],
    },
    {
      name: 'Cable Pull-through',
      slug: 'cable-pull-through',
      description: 'Hip hinge glute exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Face away from cable',
        'Pull through legs',
        'Drive hips forward',
      ],
      tips: ['Squeeze glutes', 'Don\'t squat'],
      commonMistakes: ['Squatting down', 'Using arms'],
    },
    {
      name: 'Kickbacks',
      slug: 'kickbacks',
      description: 'Glute isolation exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Cable Machine',
      instructions: [
        'Attach ankle strap',
        'Kick leg back',
        'Squeeze glute',
      ],
      tips: ['Keep leg straight', 'Control movement'],
      commonMistakes: ['Using momentum', 'Arching back'],
    },
    {
      name: 'Clamshells',
      slug: 'clamshells',
      description: 'Glute medius exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Resistance Band',
      instructions: [
        'Lie on side',
        'Open knees like clamshell',
        'Control return',
      ],
      tips: ['Keep feet together', 'Don\'t rotate body'],
      commonMistakes: ['Rolling back', 'Using hip flexors'],
    },
    {
      name: 'Frog Pumps',
      slug: 'frog-pumps',
      description: 'Glute activation exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Lie with soles together',
        'Drive hips up',
        'Squeeze and lower',
      ],
      tips: ['Knees wide', 'Full squeeze'],
      commonMistakes: ['Feet too close', 'Using back'],
    },
    {
      name: 'Single Leg Glute Bridge',
      slug: 'single-leg-glute-bridge',
      description: 'Unilateral glute exercise',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'One leg extended',
        'Drive hip up',
        'Lower with control',
      ],
      tips: ['Keep hips level', 'Full extension'],
      commonMistakes: ['Hip dropping', 'Using back'],
    },
    {
      name: 'Curtsy Lunge',
      slug: 'curtsy-lunge',
      description: 'Lunge variation for glutes',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Step behind and across',
        'Lower into curtsy',
        'Return to start',
      ],
      tips: ['Keep torso upright', 'Feel glute stretch'],
      commonMistakes: ['Leaning forward', 'Knee past toes'],
    },
    {
      name: 'Sumo Deadlift',
      slug: 'sumo-deadlift',
      description: 'Wide stance deadlift',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Wide stance, toes out',
        'Grip inside legs',
        'Drive hips forward',
      ],
      tips: ['Push floor apart', 'Chest up'],
      commonMistakes: ['Knees caving', 'Rounding back'],
    },
    {
      name: 'Good Mornings',
      slug: 'good-mornings',
      description: 'Hip hinge for glutes and hams',
      primaryMuscle: 'GLUTES' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Bar on back',
        'Hinge at hips',
        'Return to standing',
      ],
      tips: ['Push hips back', 'Slight knee bend'],
      commonMistakes: ['Rounding back', 'Going too low'],
    },

    // FULL BODY/CARDIO (10)
    {
      name: 'Burpees',
      slug: 'burpees',
      description: 'Full body conditioning',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'CARDIO' as ExerciseCategory,
      equipment: 'None',
      instructions: [
        'Drop to push-up position',
        'Do push-up',
        'Jump feet to hands',
        'Jump up',
      ],
      tips: ['Stay explosive', 'Full push-up'],
      commonMistakes: ['Skipping steps', 'Poor form'],
    },
    {
      name: 'Thrusters',
      slug: 'thrusters',
      description: 'Squat to press combo',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Hold weights at shoulders',
        'Squat down',
        'Stand and press overhead',
      ],
      tips: ['One fluid motion', 'Use legs to drive'],
      commonMistakes: ['Pausing between', 'All arms'],
    },
    {
      name: 'Man Makers',
      slug: 'man-makers',
      description: 'Complex full body exercise',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells',
      instructions: [
        'Push-up on dumbbells',
        'Row each arm',
        'Jump to squat',
        'Clean and press',
      ],
      tips: ['Flow between moves', 'Keep form'],
      commonMistakes: ['Rushing', 'Poor transitions'],
    },
    {
      name: 'Kettlebell Swings',
      slug: 'kettlebell-swings',
      description: 'Hip hinge power exercise',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Kettlebell',
      instructions: [
        'Hinge and swing between legs',
        'Drive hips forward',
        'Float kettlebell to shoulder height',
      ],
      tips: ['Hip power, not arms', 'Snap hips'],
      commonMistakes: ['Squatting', 'Using arms'],
    },
    {
      name: 'Turkish Get-ups',
      slug: 'turkish-get-ups',
      description: 'Complex stability exercise',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Kettlebell',
      instructions: [
        'Lie with weight up',
        'Stand up keeping weight overhead',
        'Reverse to lying',
      ],
      tips: ['Go slow', 'Keep arm locked'],
      commonMistakes: ['Rushing', 'Bending arm'],
    },
    {
      name: 'Battle Ropes',
      slug: 'battle-ropes',
      description: 'Upper body cardio',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'CARDIO' as ExerciseCategory,
      equipment: 'Battle Ropes',
      instructions: [
        'Hold rope ends',
        'Create waves',
        'Maintain intensity',
      ],
      tips: ['Use whole body', 'Consistent rhythm'],
      commonMistakes: ['Arms only', 'Stopping'],
    },
    {
      name: 'Rowing Machine',
      slug: 'rowing-machine',
      description: 'Full body cardio',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'CARDIO' as ExerciseCategory,
      equipment: 'Rowing Machine',
      instructions: [
        'Drive with legs',
        'Lean back',
        'Pull with arms',
      ],
      tips: ['Legs, body, arms', 'Smooth stroke'],
      commonMistakes: ['All arms', 'Poor sequencing'],
    },
    {
      name: 'Clean and Jerk',
      slug: 'clean-and-jerk',
      description: 'Olympic lift',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'OLYMPIC' as ExerciseCategory,
      equipment: 'Barbell',
      instructions: [
        'Clean bar to shoulders',
        'Dip and drive',
        'Jerk overhead',
      ],
      tips: ['Explosive', 'Full extension'],
      commonMistakes: ['Poor technique', 'No hip drive'],
    },
    {
      name: 'Sled Push',
      slug: 'sled-push',
      description: 'Full body conditioning',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Sled',
      instructions: [
        'Get low behind sled',
        'Drive forward',
        'Push through legs',
      ],
      tips: ['Stay low', 'Drive hard'],
      commonMistakes: ['Standing too tall', 'Short steps'],
    },
    {
      name: 'Farmers Walk',
      slug: 'farmers-walk',
      description: 'Loaded carry exercise',
      primaryMuscle: 'FULL_BODY' as MuscleGroup,
      category: 'STRENGTH' as ExerciseCategory,
      equipment: 'Dumbbells or Farmers Handles',
      instructions: [
        'Pick up heavy weights',
        'Walk with good posture',
        'Set down with control',
      ],
      tips: ['Shoulders back', 'Core tight'],
      commonMistakes: ['Leaning forward', 'Short steps'],
    },
  ];

  // Seed all exercises
  console.log('🌱 Seeding exercises...');
  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      update: {},
      create: exercise,
    });
    console.log(`  ✓ ${exercise.name}`);
  }

  console.log(`✅ Created ${exercises.length} exercises`);
  console.log('🎉 Database seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });